### PR TITLE
Release 0.11.2

### PR DESCRIPTION
**Pull request by mfelsche**

### CODE REVIEW

**Review by Licenser — CHANGES_REQUESTED** [review]
clippy says no :sob:

**Comment by mfelsche** [comment]
All checks have passed @Licenser

**Comment by Licenser** [comment]
Look at the files section Clippy added an annotation. It seems that warnings as error aren't turned on we should fix that

**Comment by mfelsche** [comment]
ok, enabledp edentic clippy, denied warnings and made clippy shut up. :)

**Review by Licenser — APPROVED** [review]
:rocket:

**Pull request merged**
