### PR TITLE
Fix the build script

### PR DESCRIPTION
**Pull request by mfelsche**
this creates a dependency on the `.git` folder and requires users to have git installed.

### CODE REVIEW

**Review by darach — APPROVED** [review]
LGTM

**Comment by Licenser** [comment]
How will this generate the docs for the functions? If we do not have access to the submodule? do we fetch the docs some different way?

**Comment by mfelsche** [comment]
They are part of the crate. We used to include the whole tremor-www-docs submodule in the crate.
We dont want to add a dependency on the `.git` folder being around for the build script, which is also run when doing `cargo install tremor-language-server`.

**Comment by mfelsche** [comment]
I kept the git command in the build script, but made sure, we never publish without having the submodule around.

**Review by Licenser — APPROVED** [review]

**Pull request merged**
